#不能用localhost,否则启动报异常:Unresolved address
#tcp监听的端口
tcp:
  host: 127.0.0.1
  port: 19393
# bossGroup的线程数
boss:
  thread:
    count: 4
# worker的线程数
worker:
  thread:
    count: 4
#是否使用长连接
so:
  keepalive:  true
  backlog: 100
netty:
  close:
    byte: byebye