server:
  port: 8021
spring:
  profiles:
    active: dev
    #include: redis,jdbc,mybatis,netty
    include: redis-cluster,jdbc,mybatis,netty
logging:
  level:
    com:
      lll:
        sort:
          dao:
            mapper: debug