server:
  port: 8021
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/shell?characterEncoding=utf-8
    username : root
    password : mysql6633
    driverClassName : com.mysql.cj.jdbc.Driver
  jpa:
    show-sql:true
