#redis集群配置
spring:
  redis:
    #密码
    password: zlmaster
    ## Redis数据库索引(默认为0)
    #database: 0
    ## 连接超时时间（毫秒）
    timeout: 10000
    cluster:
      #集群节点
      nodes: 127.0.0.1:16381,127.0.0.1:16382,127.0.0.1:16383,127.0.0.1:16384,127.0.0.1:16385,127.0.0.1:16386,127.0.0.1:16387,127.0.0.1:16388
      max-redirects: 5
    lettuce:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ## 连接池中的最大空闲连接
        max-idle: 10
        ## 连接池中的最小空闲连接
        min-idle: 4
