server:
  port: 8022
spring:
  profiles:
    active: dev
    #include: redis,jdbc,mybatis,netty
    include: jdbc,mybatis,rabbitmq,netty
logging:
  level:
    com:
      lll:
        sort:
          dao:
            mapper: debug