spring:
  #redis
  redis:
    #redis机器ip
    hostname: 127.0.0.1
    #redis端口
    port: 6379
    #redis密码
    password: gocom20160801
      #jedis:
    lettuce:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ## 连接池中的最大空闲连接
        max-idle: 10
        ## 连接池中的最小空闲连接
        min-idle: 4